export const ROUTES = {
  home: '/',
  about: '/about',
  services: '/services',
  serviceDetail: '/services/:slug',
  contact: '/contact',
  blog: '/blog',
  faq: '/faq',
  calculators: '/calculators',
  emiCalculator: '/calculators/emi',
  premiumCalculator: '/calculators/premium',
  policyCalculator: '/calculators/policy',
  claimTracking: '/claim-tracking',
  downloads: '/downloads',
  portal: '/portal',
  portalLogin: '/portal/login',
  portalDashboard: '/portal/dashboard',
  portalPolicies: '/portal/policies',
  portalPolicyDetail: '/portal/policies/:id',
  portalDocuments: '/portal/documents',
  portalRenewals: '/portal/renewals',
  portalClaims: '/portal/claims',
  portalProfile: '/portal/profile',
  portalNotifications: '/portal/notifications',
  portalSettings: '/portal/settings',
  reminders: '/reminders',
} as const

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES]
