import type { ServiceDetail } from '@/config/services'

export const SERVICE_PAGE_DATA: Record<string, ServiceDetail> = {
  'car-insurance': {
    slug: 'car-insurance',
    title: 'Car Insurance',
    desc: 'Comprehensive car insurance plans for your sedan, SUV, or premium vehicle with fast claims support.',
    hero: 'Secure your car with premium coverage, zero depreciation add-ons, and round-the-clock claim assistance.',
    features: [
      'Third-party and comprehensive policies',
      'Zero depreciation and roadside assistance options',
      'Fast claim support with cashless network garages',
      'Flexible add-ons and renewal support',
    ],
    details: [
      'Compare premium car insurance plans from trusted insurers.',
      'Choose the right cover for your sedan, hatchback, SUV, or luxury car.',
      'Maintain your policy with expert renewal and claim guidance.',
    ],
    note: 'Designed for drivers who want premium protection with easy claims and complete transparency.',
  },
  'bike-insurance': {
    slug: 'bike-insurance',
    title: 'Bike Insurance',
    desc: 'Smart two-wheeler cover with quick approvals, cashless claims, and tailored benefits for bikers.',
    hero: 'Protect your bike with affordable plans and premium support for roadside assistance and claims.',
    features: [
      'Comprehensive and third-party policies',
      'Add-ons like zero depreciation, engine protection, and personal accident cover',
      'Cashless garage support and fast claim settlement',
      'Flexible renewals and transfer services',
    ],
    details: [
      'Choose from leading insurers with transparent premium quotes.',
      'Get help selecting add-ons and policy features for your riding style.',
      'Enjoy smooth renewals and hassle-free claim filing.',
    ],
  },
  'commercial-vehicle-insurance': {
    slug: 'commercial-vehicle-insurance',
    title: 'Commercial Vehicle Insurance',
    desc: 'Reliable commercial vehicle insurance for fleets, cargo carriers, taxis and business vehicles.',
    hero: 'Protect your commercial fleet with cover that includes liability, cargo damage, and driver protection.',
    features: [
      'Fleet-level policies for multiple vehicles',
      'Goods-in-transit and passenger liability cover',
      'Quick claims assistance for commercial operations',
      'Policy management for renewals and compliance',
    ],
    details: [
      'Protect trucks, tempos, taxis, and delivery vehicles with business-grade coverage.',
      'Keep documentation compliant for fast approvals and renewal.',
      'Manage fleet policies with expert support at every stage.',
    ],
  },
  'health-insurance': {
    slug: 'health-insurance',
    title: 'Health Insurance',
    desc: 'Family and individual plans with cashless hospitals, wellness support, and comprehensive coverage.',
    hero: 'Keep your family healthy with carefully selected health plans that cover treatment, critical illness, and hospital stays.',
    features: [
      'Wide hospital cashless network',
      'Coverage for surgery, maternity, and critical illness',
      'No-claim bonuses and renewal benefits',
      'Wellness support and claim guidance',
    ],
    details: [
      'Compare family floater and individual plans with clear benefit summaries.',
      'Get help understanding waiting periods, co-pay, and sub-limits.',
      'Receive support for claims, renewals, and policy servicing.',
    ],
  },
  'family-health-insurance': {
    slug: 'family-health-insurance',
    title: 'Family Health Insurance',
    desc: 'Complete coverage for spouses, children, and parents with flexible family floater benefits.',
    hero: 'Protect your entire family with a single health plan that covers medical emergencies and wellness needs.',
    features: [
      'Single premium for the whole family',
      'Cashless treatment across network hospitals',
      'Maternity, daycare, and critical illness cover',
      'Easy renewals and no-claim bonuses',
    ],
    details: [
      'Choose the right family floater plan for all age groups.',
      'Compare limits, room rent options, and co-pay structures.',
      'Access seamless claim support for every family member.',
    ],
  },
  'senior-citizen-health-insurance': {
    slug: 'senior-citizen-health-insurance',
    title: 'Senior Citizen Health Insurance',
    desc: 'Specialised health cover for seniors with hospital cashless facilities and critical illness protection.',
    hero: 'Ensure care for senior family members with coverage tailored to age-related health needs.',
    features: [
      'Coverage for pre-existing conditions after waiting period',
      'Cashless hospitalisation and critical illness cover',
      'Health check-up benefits and wellness support',
      'Easy claim guidance for senior policyholders',
    ],
    details: [
      'Find affordable senior health plans with strong hospital networks.',
      'Get guidance on pre-existing conditions, waiting periods, and policy terms.',
      'Receive support for renewals and claim filing through dedicated service.',
    ],
  },
  'personal-accident-insurance': {
    slug: 'personal-accident-insurance',
    title: 'Personal Accident Insurance',
    desc: 'Protect your income and family with personal accident cover for death, disability, and hospitalization.',
    hero: 'Get financial security for accidents with fast claim support and broad coverage options.',
    features: [
      'Accidental death and disability benefits',
      'Medical expense reimbursement and daily cash support',
      'Worldwide coverage for accidents',
      'Add-on benefits for hospitalization and trauma care',
    ],
    details: [
      'Choose the right cover for individuals and families.',
      'Understand benefit limits, exclusions, and claim process clearly.',
      'Get quick assistance for filing claims and receiving payouts.',
    ],
  },
  'term-life-insurance': {
    slug: 'term-life-insurance',
    title: 'Term Life Insurance',
    desc: 'High-value term life cover to protect your family’s financial future with affordable premiums.',
    hero: 'Lock in financial security with term insurance that provides strong protection and simplicity.',
    features: [
      'High sum assured at low premiums',
      'Flexible tenure and premium payment options',
      'Optional riders for critical illness and disability',
      'Tax benefits under investment sections',
    ],
    details: [
      'Compare term policies with guaranteed death benefits and riders.',
      'Receive help selecting the right tenure and cover amount.',
      'Get dedicated support for claims, renewals, and policy servicing.',
    ],
  },
  'travel-insurance': {
    slug: 'travel-insurance',
    title: 'Travel Insurance',
    desc: 'Travel coverage for medical emergencies, baggage loss and trip delays across domestic and international journeys.',
    hero: 'Travel with confidence, knowing that health, baggage, and trip disruptions are covered globally.',
    features: [
      'Emergency medical evacuation and hospitalisation cover',
      'Trip cancellation and baggage protection',
      '24/7 travel assistance and repatriation support',
      'Coverage for business and leisure travel',
    ],
    details: [
      'Pick the right travel insurance for your destination and trip duration.',
      'Understand exclusions, pre-existing condition clauses, and claim process.',
      'Get help activating your policy and filing travel claims smoothly.',
    ],
  },
  'home-insurance': {
    slug: 'home-insurance',
    title: 'Home Insurance',
    desc: 'Protect your home and contents with comprehensive fire, theft and natural disaster coverage.',
    hero: 'Secure your home investment with coverage for property, belongings, and liability risks.',
    features: [
      'Building and contents cover',
      'Protection against fire, theft, and natural calamities',
      'Personal liability coverage',
      'Optional add-ons for electronics and valuables',
    ],
    details: [
      'Select the right cover for your home’s structure and contents.',
      'Get guidance on sum insured, policy terms, and excess.',
      'Receive claims support for repairs, replacements and liability incidents.',
    ],
  },
  'fire-insurance': {
    slug: 'fire-insurance',
    title: 'Fire Insurance',
    desc: 'Specialised fire insurance for businesses and property against fire damage and allied perils.',
    hero: 'Get powerful protection against fire, explosion, and smoke damage for your assets.',
    features: [
      'Coverage for property damage and business interruption',
      'Allied perils including lightning, explosion, and storm',
      'Custom policy options for commercial and residential assets',
      'Fast claim support and loss assessment',
    ],
    details: [
      'Understand the scope of fire and allied perils coverage.',
      'Choose the right policy for your building, equipment, and inventory.',
      'Work with advisors for claims, inspections, and loss recovery.',
    ],
  },
  'marine-insurance': {
    slug: 'marine-insurance',
    title: 'Marine Insurance',
    desc: 'Marine cover for cargo, shipping, and logistics operations with global loss protection.',
    hero: 'Protect your goods in transit with marine insurance that supports cargo, hull and freight risks.',
    features: [
      'Cargo insurance for domestic and international shipments',
      'Hull and machinery protections',
      'Marine liability and freight cover',
      'Claims support for transit damage and loss',
    ],
    details: [
      'Choose the right marine policy for your shipping needs.',
      'Understand coverage for port risks, transit damage, and delays.',
      'Receive dedicated support for cargo claim settlement.',
    ],
  },
  'engineering-insurance': {
    slug: 'engineering-insurance',
    title: 'Engineering Insurance',
    desc: 'Specialty engineering cover for contractors, contractors equipment and risks during projects.',
    hero: 'Manage engineering project risk with coverage for contractors, equipment and onsite liabilities.',
    features: [
      'Contractors plant and machinery insurance',
      'Erection all risks and material damage cover',
      'Third-party liability for construction projects',
      'Claims support for project delays and equipment damage',
    ],
    details: [
      'Protect your project with policies designed for engineering risks.',
      'Get advice on machinery insurance, erection cover, and liability exposure.',
      'Receive support for claims and incident management.',
    ],
  },
  'liability-insurance': {
    slug: 'liability-insurance',
    title: 'Liability Insurance',
    desc: 'Liability cover for businesses and professionals against third-party claims and legal expenses.',
    hero: 'Shield your business from liability claims with strong coverage for legal and financial risks.',
    features: [
      'Public and product liability coverage',
      'Professional indemnity and employer liability',
      'Legal expense protection for claims defence',
      'Custom solutions for businesses and professionals',
    ],
    details: [
      'Evaluate liability exposure and select the right protection.',
      'Get guidance on limits, deductibles, and policy conditions.',
      'Receive support for claim reporting and settlement.',
    ],
  },
  'group-health-insurance': {
    slug: 'group-health-insurance',
    title: 'Group Health Insurance',
    desc: 'Employee group health cover with cashless benefits, wellness support and corporate-friendly administration.',
    hero: 'Offer your team medical protection through group health plans that simplify policy management and claims.',
    features: [
      'Group coverage for employees and dependents',
      'Cashless hospitalization and wellness programs',
      'Customizable benefits and premium structures',
      'Easy onboarding and renewal handling',
    ],
    details: [
      'Select group health plans that suit your workforce size and budget.',
      'Understand coverage levels, network hospitals, and claims handling.',
      'Receive broker support for renewal, onboarding, and employee queries.',
    ],
  },
  'corporate-insurance': {
    slug: 'corporate-insurance',
    title: 'Corporate Insurance',
    desc: 'Comprehensive corporate risk protection for businesses, assets, and key executives.',
    hero: 'Safeguard your company with corporate insurance solutions tailored to business risks and continuity planning.',
    features: [
      'Property, liability, and business interruption cover',
      'Directors and officers liability protection',
      'Employee benefits and group health plans',
      'Risk assessment and policy advisory services',
    ],
    details: [
      'Build a corporate insurance program that addresses your business exposures.',
      'Get expert guidance on policy bundling and risk financing.',
      'Receive support for claims management and compliance.',
    ],
  },
  'mutual-funds': {
    slug: 'mutual-funds',
    title: 'Mutual Funds',
    desc: 'Investment solutions across equity, debt and hybrid funds designed for long-term wealth creation.',
    hero: 'Invest with confidence in mutual funds selected for your goals, risk profile, and financial timeline.',
    features: [
      'Access to equity, debt, and hybrid funds',
      'Portfolio guidance based on your goals',
      'Regular review and performance tracking',
      'SIP planning and systematic investment advice',
    ],
    details: [
      'Choose the right funds for growth, income, or stability.',
      'Get support setting up SIPs and managing fund allocations.',
      'Receive regular portfolio reviews and performance updates.',
    ],
  },
  'sip-investment': {
    slug: 'sip-investment',
    title: 'SIP Investment',
    desc: 'Systematic investment plans for disciplined wealth building and long-term portfolio growth.',
    hero: 'Build wealth over time with SIPs that match your savings goals and risk appetite.',
    features: [
      'Automated monthly investing in mutual funds',
      'Goal-based portfolio planning',
      'Regular review and rebalancing support',
      'Tax-efficient investing and wealth planning',
    ],
    details: [
      'Start SIPs with a clear investment plan and regular contributions.',
      'Choose funds aligned to equity, debt, or balanced objectives.',
      'Track performance and adjust allocations as your goals evolve.',
    ],
  },
  'car-loan': {
    slug: 'car-loan',
    title: 'Car Loan',
    desc: 'Flexible car loan options for new and used vehicles with easy approvals and EMI management.',
    hero: 'Drive home your new car with finance solutions that fit your budget and repayment plan.',
    features: [
      'Low-interest auto loans for new and used cars',
      'Flexible tenure and down payment options',
      'Quick approval and documentation support',
      'EMI planning and loan servicing assistance',
    ],
    details: [
      'Compare lenders and find the best auto loan rate.',
      'Get help preparing documents and submitting applications.',
      'Manage EMIs and loan closure with clear guidance.',
    ],
  },
  'bike-loan': {
    slug: 'bike-loan',
    title: 'Bike Loan',
    desc: 'Affordable bike loan options for commuters and enthusiasts with fast disbursal and easy repayment.',
    hero: 'Own your bike sooner with finance plans designed for two-wheeler buyers.',
    features: [
      'Low-interest financing for scooters and motorcycles',
      'Flexible repayment tenures and minimal documentation',
      'Quick pre-approval and application support',
      'Loan servicing and closure assistance',
    ],
    details: [
      'Choose the right bike loan based on tenure and monthly EMI.',
      'Understand documentation requirements and lender terms.',
      'Receive support through approval, disbursal, and closure.',
    ],
  },
  'commercial-vehicle-loan': {
    slug: 'commercial-vehicle-loan',
    title: 'Commercial Vehicle Loan',
    desc: 'Finance solutions for commercial vehicles, goods carriers, and transport fleets.',
    hero: 'Buy commercial vehicles with financing that supports your business use and cash flow.',
    features: [
      'Loans for trucks, tempos, and commercial fleets',
      'Custom tenures and down payment plans',
      'Assistance with documents and approvals',
      'Dedicated support for disbursal and loan management',
    ],
    details: [
      'Get the right financing for your commercial vehicle purchase.',
      'Understand repayment structures and interest costs.',
      'Work with experts for fast approval and documentation.',
    ],
  },
  'rto-services': {
    slug: 'rto-services',
    title: 'RTO Services',
    desc: 'Complete RTO services covering fitness, permits, taxes, transfers, and smart card issuance.',
    hero: 'Manage your RTO processes efficiently with expert support for every vehicle service need.',
    features: [
      'Fitness renewal and permit renewal services',
      'Road tax payments and RC transfers',
      'Hypothecation add/remove, NOC, duplicate RC, and address change',
      'National/state permit, PUC reminders, smart cards, fancy numbers, and registration support',
    ],
    details: [
      'Handle vehicle compliance with expert RTO guidance.',
      'Find support for transfers, renewal, permits, and documentation.',
      'Keep vehicle records accurate and up to date with fast service.',
    ],
  },
}
