export type ServiceCategoryItem = {
  slug: string
  label: string
}

export type ServiceCategory = {
  key: 'insurance' | 'finance' | 'rto'
  title: string
  items: ServiceCategoryItem[]
}

export type ServiceDetail = {
  slug: string
  title: string
  desc: string
  hero: string
  overview: string[]
  benefits: { title: string; description: string }[]
  features: { title: string; description: string }[]
  eligibility: string[]
  documents: string[]
  process: { title: string; description: string }[]
  faqs: { question: string; answer: string }[]
  coverage: string[]
  exclusions: string[]
  addOns: string[]
  premiumFactors: string[]
  tips: string[]
  whyChoose: string[]
  related: { slug: string; label: string }[]
  note?: string
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    key: 'insurance',
    title: 'Insurance',
    items: [
      { slug: 'car-insurance', label: 'Car Insurance' },
      { slug: 'bike-insurance', label: 'Bike Insurance' },
      { slug: 'health-insurance', label: 'Health Insurance' },
      { slug: 'family-health-insurance', label: 'Family Health Insurance' },
      { slug: 'senior-citizen-health-insurance', label: 'Senior Citizen Health Insurance' },
      { slug: 'personal-accident-insurance', label: 'Personal Accident Insurance' },
      { slug: 'term-life-insurance', label: 'Term Life Insurance' },
      { slug: 'travel-insurance', label: 'Travel Insurance' },
      { slug: 'home-insurance', label: 'Home Insurance' },
      { slug: 'fire-insurance', label: 'Fire Insurance' },
      { slug: 'marine-insurance', label: 'Marine Insurance' },
      { slug: 'engineering-insurance', label: 'Engineering Insurance' },
      { slug: 'liability-insurance', label: 'Liability Insurance' },
      { slug: 'group-health-insurance', label: 'Group Health Insurance' },
      { slug: 'corporate-insurance', label: 'Corporate Insurance' },
    ],
  },
  {
    key: 'finance',
    title: 'Finance',
    items: [
      { slug: 'mutual-funds', label: 'Mutual Funds' },
      { slug: 'sip-investment', label: 'SIP Investment' },
      { slug: 'vehicle-finance', label: 'Vehicle Finance' },
      { slug: 'car-loan', label: 'Car Loan' },
      { slug: 'bike-loan', label: 'Bike Loan' },
      { slug: 'commercial-vehicle-loan', label: 'Commercial Vehicle Loan' },
      { slug: 'home-loan', label: 'Home Loan' },
      { slug: 'business-loan', label: 'Business Loan' },
    ],
  },
  {
    key: 'rto',
    title: 'RTO Services',
    items: [
      { slug: 'rto-services', label: 'RTO Services' },
      { slug: 'driving-licence', label: 'Driving Licence' },
      { slug: 'learning-licence', label: 'Learning Licence' },
      { slug: 'rc-transfer', label: 'RC Transfer' },
      { slug: 'hypothecation', label: 'Hypothecation' },
      { slug: 'noc', label: 'NOC' },
      { slug: 'fitness', label: 'Fitness' },
      { slug: 'permit', label: 'Permit' },
      { slug: 'tax', label: 'Tax' },
    ],
  },
]

export const SERVICE_DETAILS: Record<string, ServiceDetail> = {
  'car-insurance': {
    slug: 'car-insurance',
    title: 'Car Insurance',
    desc: 'Comprehensive car insurance plans for your sedan, SUV, or premium vehicle with fast claims support.',
    hero: 'Secure your car with premium coverage, zero depreciation add-ons, and round-the-clock claim assistance.',
    overview: [
      'Car insurance shields your vehicle against accidents, theft, fire, and third-party liability.',
      'Choose between comprehensive and third-party plans based on your protection needs.',
      'Add coverage for roadside assistance, personal accident, and engine protection.',
    ],
    benefits: [
      { title: 'Wide Coverage', description: 'Protect your vehicle from damage, theft, fire, and third-party claims.' },
      { title: 'Fast Claims', description: 'Quick claim settlement through cashless garages and dedicated support.' },
      { title: 'Flexible Add-ons', description: 'Choose zero depreciation, roadside assistance, and engine covers.' },
    ],
    features: [
      { title: 'Third-Party Liability', description: 'Meets legal requirements and protects against third-party damages.' },
      { title: 'Comprehensive Cover', description: 'Covers own-damage, theft, fire, and natural calamities.' },
      { title: 'Add-on Options', description: 'Select extra protections like zero depreciation and return to invoice.' },
      { title: 'Quick Renewals', description: 'Get policy reminders and smooth renewals through our team.' },
    ],
    eligibility: [
      'Vehicle registered in your name or your organization’s name',
      'Valid driving licence of the vehicle driver',
      'Vehicle details including RC book and previous insurance',
    ],
    documents: [
      'Vehicle registration certificate (RC book)',
      'Valid driving licence of policyholder/driver',
      'Previous insurance policy (if renewing)',
      'PAN card or Aadhaar card for identity verification',
    ],
    process: [
      { title: 'Quote & Compare', description: 'Review premium options and coverage details from trusted insurers.' },
      { title: 'Apply Online', description: 'Submit your vehicle and personal details through our secure process.' },
      { title: 'Policy Issuance', description: 'Receive your insurance documents electronically after approval.' },
      { title: 'Claims Support', description: 'Access help for filing claims and getting cashless service.' },
    ],
    faqs: [
      { question: 'What is the difference between third-party and comprehensive cover?', answer: 'Third-party covers damages to others, while comprehensive covers your vehicle and third-party liabilities.' },
      { question: 'Can I transfer my existing car insurance?', answer: 'Yes, we support policy transfers and renewals for smooth ownership changes.' },
      { question: 'Do I need a car insurance renewal reminder?', answer: 'Yes, we provide renewal alerts to help avoid coverage lapses.' },
    ],
    coverage: [
      'Own-damage and theft cover',
      'Third-party liability',
      'Fire and natural calamities',
      'Personal accident cover',
    ],
    exclusions: [
      'Driver under alcohol or drug influence',
      'Mechanical breakdown or wear and tear',
      'Intentional damage and racing use',
    ],
    addOns: [
      'Zero depreciation',
      'Roadside assistance',
      'Engine and gearbox protection',
      'Return to invoice cover',
    ],
    premiumFactors: [
      'Vehicle make, model, and age',
      'IDV and policy cover type',
      'No-claim bonus and claim history',
      'Add-on cover selections',
    ],
    tips: [
      'Choose a higher voluntary deductible for lower premiums.',
      'Maintain a clean claim history for reward discounts.',
      'Compare insurer offers before renewal.',
    ],
    whyChoose: [
      'Premium guidance from expert advisors.',
      'Fast claims settlement and cashless garage support.',
      'Customised cover for every vehicle type.',
    ],
    related: [
      { slug: 'vehicle-finance', label: 'Vehicle Finance' },
      { slug: 'car-loan', label: 'Car Loan' },
      { slug: 'personal-accident-insurance', label: 'Personal Accident Insurance' },
    ],
    note: 'Get tailored car insurance plus dedicated claims support from Balaji Policy Matrix LLP.',
  },
  'bike-insurance': {
    slug: 'bike-insurance',
    title: 'Bike Insurance',
    desc: 'Affordable two-wheeler insurance with cashless claim support and tailored coverage.',
    hero: 'Protect your ride with flexible bike insurance designed for commuters and leisure riders.',
    overview: [
      'Bike insurance covers third-party liability and damage to your vehicle.',
      'Choose add-ons for zero depreciation, roadside assistance, and PA cover.',
      'Easy renewals and quick claim support ensure uninterrupted protection.',
    ],
    benefits: [
      { title: 'Cashless Repairs', description: 'Access a wide network of garages for fast claim settlements.' },
      { title: 'Affordable Premiums', description: 'Competitive plans for all bike models and ages.' },
      { title: 'Flexible Coverage', description: 'Select add-ons and deductible options to fit your needs.' },
    ],
    features: [
      { title: 'Third-Party Cover', description: 'Comply with law and protect third-party damages.' },
      { title: 'Comprehensive Cover', description: 'Includes own-damage, theft, and fire protection.' },
      { title: 'Roadside Assistance', description: 'Help with breakdowns, towing, and emergency service.' },
      { title: 'Personal Accident Cover', description: 'Protect the rider with accident and medical expense benefits.' },
    ],
    eligibility: [
      'Valid driving licence for the two-wheeler rider',
      'RC book showing vehicle ownership',
      'Previous policy details for renewals',
    ],
    documents: [
      'Two-wheeler registration certificate (RC)',
      'Driver’s licence copy',
      'Previous insurance policy (if applicable)',
      'Identity proof like Aadhaar or PAN card',
    ],
    process: [
      { title: 'Select Plan', description: 'Compare bike insurance plans and add-on options.' },
      { title: 'Submit Documents', description: 'Provide RC, licence and identity documents online.' },
      { title: 'Receive Policy', description: 'Get your digital policy instantly after verification.' },
      { title: 'Claim Support', description: 'Contact our team for quick claim filing and repairs.' },
    ],
    faqs: [
      { question: 'Is bike insurance mandatory?', answer: 'Yes, third-party bike insurance is mandatory under motor insurance law.' },
      { question: 'Can I add accessories to my bike insurance?', answer: 'Yes, accessories and add-ons can be included for extra protection.' },
      { question: 'How is the premium calculated?', answer: 'Premium depends on bike model, cubic capacity, location, and add-ons chosen.' },
    ],
    coverage: [
      'Third-party liability',
      'Own-damage cover',
      'Theft and fire protection',
      'Personal accident cover',
    ],
    exclusions: [
      'Riding without a valid licence',
      'Wear and tear or mechanical failure',
      'Use for racing or unauthorized activities',
    ],
    addOns: [
      'Zero depreciation',
      'Engine protection',
      'Roadside assistance',
      'Consumables cover',
    ],
    premiumFactors: [
      'Bike model and engine capacity',
      'Policy type and add-ons',
      'Location and claim history',
      'Insurer discounts and no-claim bonus',
    ],
    tips: [
      'Renew before expiry to preserve no-claim bonus.',
      'Choose only required add-ons to optimise premium.',
      'Keep service records handy for claim support.',
    ],
    whyChoose: [
      'Fast, transparent bike insurance advice.',
      'Wide cashless garage support and claim service.',
      'Personalised plans for commuters and enthusiasts.',
    ],
    related: [
      { slug: 'car-insurance', label: 'Car Insurance' },
      { slug: 'bike-loan', label: 'Bike Loan' },
      { slug: 'vehicle-finance', label: 'Vehicle Finance' },
    ],
    note: 'Rider safety and bike protection delivered with premium service support.',
  },
  'commercial-vehicle-insurance': {
    slug: 'commercial-vehicle-insurance',
    title: 'Commercial Vehicle Insurance',
    desc: 'Business insurance for trucks, cargo carriers, taxis and transport vehicles.',
    hero: 'Protect your commercial fleet with specialized insurance designed for business operations.',
    overview: [
      'Covers vehicles used for goods transport, passenger services, and commercial delivery.',
      'Includes liability, own-damage, and transit cover.',
      'Designed for compliance, quick claims, and fleet risk management.',
    ],
    benefits: [
      { title: 'Fleet Protection', description: 'Keep your commercial vehicles insured and compliant.' },
      { title: 'Liability Cover', description: 'Protect against third-party and passenger claims.' },
      { title: 'Business Continuity', description: 'Ensure cash flow during repairs or replacements.' },
    ],
    features: [
      { title: 'Goods-in-Transit Cover', description: 'Protect merchandise and cargo during transportation.' },
      { title: 'Third-Party Liability', description: 'Legal compliance for commercial operations.' },
      { title: 'Own-Damage Cover', description: 'Repair and replacement support for vehicle damage.' },
      { title: 'Add-on Covers', description: 'Choose driver protection and emergency support packages.' },
    ],
    eligibility: [
      'Commercial vehicle registration and RC documents',
      'Driver licence and fitness certificates',
      'Business ownership or fleet details',
    ],
    documents: [
      'Vehicle registration certificate',
      'Driver licence copies',
      'Commercial permit and fitness certificate',
      'Proof of business ownership or GST details',
    ],
    process: [
      { title: 'Risk Assessment', description: 'Review vehicle type, usage, and business profile.' },
      { title: 'Policy Recommendation', description: 'Choose coverage suited to fleet size and operation.' },
      { title: 'Documentation', description: 'Submit RC, permits, and business records.' },
      { title: 'Support & Claims', description: 'Access dedicated claim assistance for commercial losses.' },
    ],
    faqs: [
      { question: 'Does commercial insurance cover cargo damage?', answer: 'Yes, cargo cover protects goods during transit and storage.' },
      { question: 'Can I insure a fleet of vehicles under one policy?', answer: 'Yes, fleet policies are available for multiple commercial vehicles.' },
      { question: 'Is passenger liability included?', answer: 'Passenger liability is available as part of commercial vehicle packages.' },
    ],
    coverage: [
      'Third-party liability',
      'Own-damage',
      'Cargo and goods-in-transit',
      'Driver and passenger protection',
    ],
    exclusions: [
      'Unauthorized use or illegal passenger activities',
      'Uninsured driver operation',
      'Normal wear and tear',
    ],
    addOns: [
      'Driver personal accident',
      'Goods-in-transit insurance',
      'Roadside assistance',
      'Legal expenses cover',
    ],
    premiumFactors: [
      'Vehicle type and cargo category',
      'Fleet size and geography',
      'Driver experience and claims history',
      'Add-on coverage choices',
    ],
    tips: [
      'Maintain vehicle fitness and permit documents proactively.',
      'Choose policies aligned to vehicle usage and cargo type.',
      'Keep records of drivers and incident reports for claims.',
    ],
    whyChoose: [
      'Specialised commercial insurance expertise.',
      'Fast claims support for fleet operations.',
      'Flexible coverage for passenger and cargo risk.',
    ],
    related: [
      { slug: 'rto-services', label: 'RTO Services' },
      { slug: 'commercial-vehicle-loan', label: 'Commercial Vehicle Loan' },
      { slug: 'liability-insurance', label: 'Liability Insurance' },
    ],
    note: 'Business vehicle protection and fleet insurance crafted for commercial needs.',
  },
  'health-insurance': {
    slug: 'health-insurance',
    title: 'Health Insurance',
    desc: 'Family and individual medical coverage with wide cashless support and wellness benefits.',
    hero: 'Protect your health with plans that cover treatment, hospitalization, and preventive care.',
    overview: [
      'Health insurance provides financial protection for medical expenses.',
      'Select individual or family plans with cashless hospitalization.',
      'Access wellness and preventive benefits in addition to treatment cover.',
    ],
    benefits: [
      { title: 'Cashless Hospitals', description: 'Avail health benefits at network hospitals without upfront costs.' },
      { title: 'Wide Coverage', description: 'Includes hospitalization, surgery, maternity, and critical illness.' },
      { title: 'Renewal Perks', description: 'Enjoy no-claim bonuses and lifelong renewability.' },
    ],
    features: [
      { title: 'Hospitalization Cover', description: 'Pay for inpatient treatment and surgery bills.' },
      { title: 'Daycare Procedures', description: 'Include minor treatment and outpatient procedures.' },
      { title: 'Pre- and Post-Hospitalization', description: 'Benefit from medical care around hospitalization.' },
      { title: 'Critical Illness', description: 'Additional protection for serious conditions.' },
    ],
    eligibility: [
      'Individual or family members aged between 18 and 65',
      'Completed health declaration and application form',
      'Existing medical records for senior plans',
    ],
    documents: [
      'Identity proof (Aadhaar/PAN)',
      'Address proof',
      'Medical history documents if applicable',
      'Previous policy details for renewal',
    ],
    process: [
      { title: 'Plan Recommendation', description: 'Match your health needs with appropriate plans.' },
      { title: 'Application Submission', description: 'Provide essentials like ID, address and health history.' },
      { title: 'Policy Issuance', description: 'Receive coverage documents and digital policy copy.' },
      { title: 'Claims Assistance', description: 'Get support for cashless admission and claim settlement.' },
    ],
    faqs: [
      { question: 'Can I buy health insurance online?', answer: 'Yes, we help you select and purchase the right health plan digitally.' },
      { question: 'Does health insurance cover maternity?', answer: 'Many plans offer maternity coverage after the waiting period.' },
      { question: 'What is a family floater plan?', answer: 'A family floater covers all family members under a single sum insured.' },
    ],
    coverage: [
      'Hospitalization expenses',
      'Pre- and post-hospitalization care',
      'Daycare procedures',
      'Critical illness treatment',
    ],
    exclusions: [
      'Pre-existing diseases during waiting period',
      'Cosmetic surgery and non-medical expenses',
      'Claims from intoxication or self-harm',
    ],
    addOns: [
      'Maternity cover',
      'Health check-ups',
      'Hospital cash',
      'Room rent waiver',
    ],
    premiumFactors: [
      'Age and health profile',
      'Sum insured and policy type',
      'Family size and medical history',
      'Claim history and wellness benefits',
    ],
    tips: [
      'Buy early to lower premium increases with age.',
      'Choose adequate sum insured for your family.',
      'Review network hospitals before buying a plan.',
    ],
    whyChoose: [
      'Expert health insurance advice for families.',
      'Assistance with claim approvals and hospital admissions.',
      'Personalized plans for each life stage.',
    ],
    related: [
      { slug: 'family-health-insurance', label: 'Family Health Insurance' },
      { slug: 'group-health-insurance', label: 'Group Health Insurance' },
      { slug: 'corporate-insurance', label: 'Corporate Insurance' },
    ],
    note: 'Health coverage that balances premium value and reliable claim support.',
  },
  'family-health-insurance': {
    slug: 'family-health-insurance',
    title: 'Family Health Insurance',
    desc: 'Complete family coverage with cashless hospitals and strong wellness benefits.',
    hero: 'Keep your loved ones protected under one premium plan for the whole family.',
    overview: [
      'Family floater plans cover spouses, children, and parents.',
      'Offers supported cashless hospitalization and maternity benefits.',
      'Designed for convenience and comprehensive family protection.',
    ],
    benefits: [
      { title: 'Single Premium', description: 'One policy covers all family members.' },
      { title: 'Broad Hospital Network', description: 'Access cashless hospitals nationwide.' },
      { title: 'Wellness Programs', description: 'Includes preventive and wellbeing benefits.' },
    ],
    features: [
      { title: 'Family Floater Cover', description: 'Shared sum insured for the entire family.' },
      { title: 'Maternity Benefits', description: 'Covers pre-natal and post-natal care where available.' },
      { title: 'No-Claim Bonus', description: 'Database benefits for healthy years.' },
      { title: 'Daycare Procedures', description: 'Treatment for short-stay medical procedures.' },
    ],
    eligibility: [
      'Family members residing together',
      'Valid identity and address proof for all proposed members',
      'Medical history details for senior dependents',
    ],
    documents: [
      'Identity and address proof',
      'Family member details with age proofs',
      'Previous health insurance policy if any',
      'Medical reports for pre-existing conditions',
    ],
    process: [
      { title: 'Quote Comparison', description: 'Evaluate family plans by coverage and premium.' },
      { title: 'Submit Documents', description: 'Complete application with member details and proofs.' },
      { title: 'Policy Issuance', description: 'Receive digital policy documents for the family plan.' },
      { title: 'Claims Support', description: 'Use cashless network hospitals for treatment.' },
    ],
    faqs: [
      { question: 'Can parents be included in a family floater?', answer: 'Yes, many plans allow parents and children to be included.' },
      { question: 'How is sum insured shared?', answer: 'The covered amount is available to the entire family collectively.' },
      { question: 'Does it cover maternity?', answer: 'Certain plans include maternity benefits after waiting period.' },
    ],
    coverage: [
      'Family hospitalization cover',
      'Maternity and daycare expenses',
      'Pre- and post-hospitalization care',
      'Health check-up benefits',
    ],
    exclusions: [
      'Pre-existing conditions during waiting period',
      'Self-inflicted injuries',
      'Unapproved treatments and procedures',
    ],
    addOns: [
      'Maternity',
      'Hospital cash',
      'Critical illness',
      'Wellness cover',
    ],
    premiumFactors: [
      'Family size and age profile',
      'Sum insured and chosen benefits',
      'Location and network hospital access',
      'Policy bonuses and claim history',
    ],
    tips: [
      'Compare plans by benefit coverage and premium.',
      'Include only needed dependents to manage premium.',
      'Use cashless hospitals to reduce out-of-pocket costs.',
    ],
    whyChoose: [
      'Family-first protection with trusted insurers.',
      'Streamlined claims for multiple members.',
      'Personalized support for renewals and policy servicing.',
    ],
    related: [
      { slug: 'health-insurance', label: 'Health Insurance' },
      { slug: 'senior-citizen-health-insurance', label: 'Senior Citizen Health Insurance' },
      { slug: 'group-health-insurance', label: 'Group Health Insurance' },
    ],
  },
  'senior-citizen-health-insurance': {
    slug: 'senior-citizen-health-insurance',
    title: 'Senior Citizen Health Insurance',
    desc: 'Health coverage designed for seniors with pre-existing condition support and cashless benefits.',
    hero: 'Provide senior family members with reliable medical protection and hospitalization cover.',
    overview: [
      'Senior citizen health insurance covers age-related medical expenses.',
      'Includes cashless hospitalisation and special senior care benefits.',
      'Designed for smooth renewals and claim assistance for seniors.',
    ],
    benefits: [
      { title: 'Senior-Friendly Cover', description: 'Policies suited for age-related health needs.' },
      { title: 'Cashless Network', description: 'Access cashless treatment at wide hospitals.' },
      { title: 'Pre-Existing Condition Support', description: 'Coverage after waiting period for personal health conditions.' },
    ],
    features: [
      { title: 'Hospitalization and surgery cover', description: 'Support for inpatient and critical treatments.' },
      { title: 'Pre-existing disease cover', description: 'Protection after specified waiting periods.' },
      { title: 'Health monitoring benefits', description: 'Check-ups and wellness incentives for seniors.' },
      { title: 'Easy renewals', description: 'Renew policies with minimal disruption.' },
    ],
    eligibility: [
      'Applicants aged 60 years and above',
      'Medical history declaration',
      'Address and identity proof documents',
    ],
    documents: [
      'Aadhaar or PAN for identity proof',
      'Address proof',
      'Medical reports for pre-existing conditions',
      'Previous health policy details if available',
    ],
    process: [
      { title: 'Plan Selection', description: 'Choose coverage suited to senior health needs.' },
      { title: 'Medical Evaluation', description: 'Submit reports and health history for approval.' },
      { title: 'Policy Activation', description: 'Receive the policy after underwriting and documentation.' },
      { title: 'Claim Support', description: 'Get help for hospitalisation and cashless claims.' },
    ],
    faqs: [
      { question: 'Are pre-existing conditions covered immediately?', answer: 'Typically after a waiting period, depending on policy terms.' },
      { question: 'Can seniors renew existing policies?', answer: 'Yes, renewals remain available with continuous coverage.' },
      { question: 'Do I get cashless hospitalization?', answer: 'Yes, most plans offer a cashless hospital network for seniors.' },
    ],
    coverage: [
      'Senior hospitalization expenses',
      'Pre-existing diseases after waiting period',
      'Daycare treatments',
      'Post-hospitalization care',
    ],
    exclusions: [
      'Cosmetic procedures',
      'Non-medical expenditures',
      'Intentional self-harm',
    ],
    addOns: [
      'Hospital cash',
      'Critical illness',
      'Health check-ups',
      'Ayush treatment cover',
    ],
    premiumFactors: [
      'Age and medical history',
      'Sum insured and policy tenure',
      'Pre-existing conditions',
      'Preferred hospital network',
    ],
    tips: [
      'Review waiting periods before policy selection.',
      'Choose plans with wide hospital access.',
      'Keep medical records handy for claims.',
    ],
    whyChoose: [
      'Senior-specific health protection with personal service.',
      'Assistance with underwriting and renewals.',
      'Reliable cashless support for hospital stays.',
    ],
    related: [
      { slug: 'health-insurance', label: 'Health Insurance' },
      { slug: 'family-health-insurance', label: 'Family Health Insurance' },
      { slug: 'corporate-insurance', label: 'Corporate Insurance' },
    ],
  },
  'term-life-insurance': {
    slug: 'term-life-insurance',
    title: 'Term Life Insurance',
    desc: 'Affordable term life cover with high protection and optional riders for family security.',
    hero: 'Secure your family’s future with term life insurance that delivers strong protection and financial certainty.',
    overview: [
      'Term insurance provides high death benefit for low premiums.',
      'Optional riders add coverage for illness and disability.',
      'Focuses on pure protection without investment components.',
    ],
    benefits: [
      { title: 'High Cover', description: 'Large protection amounts for dependents.' },
      { title: 'Low Premiums', description: 'Affordable rates for strong life cover.' },
      { title: 'Rider Options', description: 'Enhance protection with critical illness and disability riders.' },
    ],
    features: [
      { title: 'Pure Risk Cover', description: 'Death benefit only, with no savings element.' },
      { title: 'Flexible Term', description: 'Choose policy duration that fits your financial plan.' },
      { title: 'Optional Riders', description: 'Add critical illness, accidental death and waiver of premium.' },
      { title: 'Tax Benefits', description: 'Premiums may be eligible for tax deductions.' },
    ],
    eligibility: [
      'Applicants aged 18 to 65 years',
      'Complete health declaration',
      'Valid identity proof and address details',
    ],
    documents: [
      'Identity proof such as Aadhaar or PAN',
      'Address proof',
      'Age proof documents',
      'Medical reports if requested by the insurer',
    ],
    process: [
      { title: 'Quote Evaluation', description: 'Compare term cover options from trusted insurers.' },
      { title: 'Application Completion', description: 'Submit personal and health information accurately.' },
      { title: 'Policy Issuance', description: 'Receive coverage documents and digital certificate.' },
      { title: 'Ongoing Service', description: 'Get support for renewals, riders and claim assistance.' },
    ],
    faqs: [
      { question: 'What is term life insurance?', answer: 'A policy that pays a death benefit if the insured dies during the policy term.' },
      { question: 'Can I add critical illness cover?', answer: 'Yes, riders are available to enhance term insurance protection.' },
      { question: 'Is maturity benefit available?', answer: 'No, term insurance generally has no maturity benefit unless it is a return of premium policy.' },
    ],
    coverage: [
      'Death benefit for beneficiaries',
      'Accidental death cover',
      'Optional critical illness rider',
      'Disability protection rider',
    ],
    exclusions: [
      'Suicide within policy waiting period',
      'Self-inflicted injuries',
      'Non-disclosure of medical history',
    ],
    addOns: [
      'Critical illness rider',
      'Accidental death benefit',
      'Waiver of premium',
      'Income benefit rider',
    ],
    premiumFactors: [
      'Age and health status',
      'Sum assured and policy term',
      'Lifestyle and occupation',
      'Riders selected',
    ],
    tips: [
      'Buy early for lower premiums and more coverage.',
      'Choose a term length that covers major liabilities.',
      'Keep medical records transparent for underwriting.',
    ],
    whyChoose: [
      'Pure protection with expert policy guidance.',
      'Fast application and claim support.',
      'Trusted service from Balaji Policy Matrix LLP.',
    ],
    related: [
      { slug: 'personal-accident-insurance', label: 'Personal Accident Insurance' },
      { slug: 'home-insurance', label: 'Home Insurance' },
      { slug: 'liability-insurance', label: 'Liability Insurance' },
    ],
  },
  'travel-insurance': {
    slug: 'travel-insurance',
    title: 'Travel Insurance',
    desc: 'Travel coverage for medical emergencies, baggage loss, trip cancellation and delay protection.',
    hero: 'Travel safely with comprehensive coverage for domestic and international journeys.',
    overview: [
      'Travel insurance protects you from medical, baggage and trip risks during travel.',
      'Choose plans for single-trip, annual multi-trip, or family travel.',
      'Includes emergency assistance and policy support while abroad.',
    ],
    benefits: [
      { title: 'Emergency Medical Cover', description: 'Support for medical emergencies while travelling.' },
      { title: 'Trip Protection', description: 'Cover for cancellations, delays and lost baggage.' },
      { title: 'Worldwide Assistance', description: '24/7 support for travelers across destinations.' },
    ],
    features: [
      { title: 'Medical Expense Cover', description: 'Pays treatment costs abroad or domestically.' },
      { title: 'Baggage Protection', description: 'Covers lost or stolen luggage.' },
      { title: 'Trip Cancellation', description: 'Reimburses eligible cancellation expenses.' },
      { title: 'Travel Assistance', description: 'Access emergency helpline and policy support.' },
    ],
    eligibility: [
      'Valid passport and travel documents for international trips',
      'Accurate itinerary and travel details',
      'Health declaration for pre-existing conditions if needed',
    ],
    documents: [
      'Passport copy for international coverage',
      'Travel itinerary and ticket details',
      'Identity proof for domestic trips',
      'Medical history declarations if applicable',
    ],
    process: [
      { title: 'Plan Selection', description: 'Choose domestic or international travel cover.' },
      { title: 'Provide Travel Details', description: 'Submit destination, dates and traveler information.' },
      { title: 'Policy Confirmation', description: 'Receive instant travel insurance documents.' },
      { title: 'Emergency Support', description: 'Use policy assistance for claims and travel help.' },
    ],
    faqs: [
      { question: 'Do I need travel insurance for domestic trips?', answer: 'Yes, it covers medical emergencies, baggage loss, and trip delays domestically too.' },
      { question: 'Can I buy insurance after booking travel?', answer: 'Yes, but buy as early as possible for better protection.' },
      { question: 'Does it cover pre-existing conditions?', answer: 'Some plans cover them with declaration and extra premium.' },
    ],
    coverage: [
      'Emergency medical expenses',
      'Loss of checked baggage',
      'Trip cancellation and delays',
      'Personal liability and repatriation',
    ],
    exclusions: [
      'Adventure sports without cover',
      'Pre-existing conditions not declared',
      'War and civil unrest',
    ],
    addOns: [
      'Adventure sports cover',
      'Rental car protection',
      'Travel delay cover',
      'Personal liability extension',
    ],
    premiumFactors: [
      'Trip destination and duration',
      'Age of the traveler',
      'Coverage limits chosen',
      'Add-on options selected',
    ],
    tips: [
      'Buy travel insurance before departure.',
      'Compare emergency medical limits and exclusions.',
      'Keep digital copies of your policy while travelling.',
    ],
    whyChoose: [
      'Travel insurance with reliable global support.',
      'Quick policy activation and emergency help.',
      'Custom plans for leisure and business travel.',
    ],
    related: [
      { slug: 'health-insurance', label: 'Health Insurance' },
      { slug: 'personal-accident-insurance', label: 'Personal Accident Insurance' },
      { slug: 'term-life-insurance', label: 'Term Life Insurance' },
    ],
  },
  'home-insurance': {
    slug: 'home-insurance',
    title: 'Home Insurance',
    desc: 'Protect your home and belongings from fire, theft, natural disasters and liability with comprehensive cover.',
    hero: 'Secure your home asset with protection for structure, contents, and family liability risks.',
    overview: [
      'Home insurance covers property damage and contents loss.',
      'Suitable for homeowners and landlords seeking asset protection.',
      'Includes fire, theft, flood, storm and liability cover where applicable.',
    ],
    benefits: [
      { title: 'Asset Protection', description: 'Cover your home structure and belongings against damage and loss.' },
      { title: 'Liability Cover', description: 'Protect against accidents on your property.' },
      { title: 'Peace of Mind', description: 'Stay protected from unexpected disasters and repairs.' },
    ],
    features: [
      { title: 'Building Cover', description: 'Protect the home structure and permanent fixtures.' },
      { title: 'Contents Cover', description: 'Insure furniture, appliances, and valuables.' },
      { title: 'Natural Disaster Protection', description: 'Cover damages from storms, fire, and floods.' },
      { title: 'Liability Benefits', description: 'Protect against accidents on your property.' },
    ],
    eligibility: [
      'Home owned or rented by the applicant',
      'Property located in covered regions',
      'Copies of title deeds or lease agreements',
    ],
    documents: [
      'Property ownership or rental proof',
      'Address proof',
      'Inventory list of contents',
      'Photographs of property and value assessment',
    ],
    process: [
      { title: 'Property Evaluation', description: 'Review property details and insurable value.' },
      { title: 'Quote Selection', description: 'Choose coverage and optional benefits.' },
      { title: 'Policy Issuance', description: 'Receive insurance documents electronically.' },
      { title: 'Claims Support', description: 'File claims for repairs, replacements or liability incidents.' },
    ],
    faqs: [
      { question: 'Does home insurance cover theft?', answer: 'Yes, contents insurance protects against theft and burglary.' },
      { question: 'Can I add earthquake cover?', answer: 'Yes, natural disaster add-ons are available for eligible properties.' },
      { question: 'What is liability coverage?', answer: 'It protects you if someone is injured on your property.' },
    ],
    coverage: [
      'Building and structure protection',
      'Contents and valuables coverage',
      'Fire and natural calamity protection',
      'Legal liability for third-party accidents',
    ],
    exclusions: [
      'Intentional damage and neglect',
      'Wear and tear',
      'Uninsured valuables or cash',
    ],
    addOns: [
      'Flood cover',
      'Jewellery and electronics cover',
      'Household assistance',
      'Earthquake damage protection',
    ],
    premiumFactors: [
      'Property construction and value',
      'Location and natural risk exposure',
      'Contents value and security features',
      'Optional add-ons selected',
    ],
    tips: [
      'Review policy limits for high-value items.',
      'Document your contents with photographs.',
      'Choose suitable add-ons for your home location.',
    ],
    whyChoose: [
      'Thoughtful home protection and fast claim help.',
      'Expert advice for property and contents coverage.',
      'Clear policy terms and personalized service.',
    ],
    related: [
      { slug: 'fire-insurance', label: 'Fire Insurance' },
      { slug: 'personal-accident-insurance', label: 'Personal Accident Insurance' },
      { slug: 'home-loan', label: 'Home Loan' },
    ],
  },
  'fire-insurance': {
    slug: 'fire-insurance',
    title: 'Fire Insurance',
    desc: 'Protect your property and business from fire, explosion and allied perils with specialized coverage.',
    hero: 'Keep your assets safe from fire damage and unexpected losses with commercial-grade protection.',
    overview: [
      'Fire insurance covers physical damage caused by fire and allied perils.',
      'Ideal for businesses, warehouses, and residential properties.',
      'Includes property damage, loss of stock, and business interruption support.',
    ],
    benefits: [
      { title: 'Property Security', description: 'Protect buildings and equipment from fire-related damage.' },
      { title: 'Business Continuity', description: 'Recover faster from fire incidents and interruptions.' },
      { title: 'Claim Guidance', description: 'Expert support for loss assessment and settlement.' },
    ],
    features: [
      { title: 'Fire Damage Cover', description: 'Protection against fire and explosion-related losses.' },
      { title: 'Allied Perils', description: 'Includes lightning, storms, and smoke damage.' },
      { title: 'Stock and Inventory Protection', description: 'Cover goods stored on the premises.' },
      { title: 'Business Interruption', description: 'Support for income loss following damage.' },
    ],
    eligibility: [
      'Property or business ownership details',
      'Asset value declaration',
      'Risk assessment information',
    ],
    documents: [
      'Property ownership proof',
      'Asset value inventory',
      'Safety and fire prevention certificates if available',
      'Business registration documents for commercial properties',
    ],
    process: [
      { title: 'Risk Evaluation', description: 'Assess your property and fire risk factors.' },
      { title: 'Quote Selection', description: 'Choose a policy that fits your property type.' },
      { title: 'Policy Issuance', description: 'Receive insurer documents and coverage details.' },
      { title: 'Loss Settlement', description: 'Claim support for fire damage recovery.' },
    ],
    faqs: [
      { question: 'Does fire insurance cover explosions?', answer: 'Yes, allied perils like explosions are included under most fire policies.' },
      { question: 'Can I insure my warehouse stock?', answer: 'Yes, inventory and goods can be covered under fire insurance.' },
      { question: 'Is business interruption included?', answer: 'Many policies offer optional interruption cover for income loss.' },
    ],
    coverage: [
      'Fire damage',
      'Explosion losses',
      'Smoke damage',
      'Allied perils and electrical faults',
    ],
    exclusions: [
      'Arson and intentional damage',
      'Wear and tear',
      'Unmaintained electrical systems',
    ],
    addOns: [
      'Business interruption cover',
      'Stock protection',
      'Glass breakage cover',
      'Special perils protection',
    ],
    premiumFactors: [
      'Property value and construction type',
      'Fire safety systems',
      'Stock value and hazardous materials',
      'Claim history and risk controls',
    ],
    tips: [
      'Invest in fire safety systems to reduce premiums.',
      'Provide accurate asset valuation for coverage.',
      'Review policy exclusions carefully.',
    ],
    whyChoose: [
      'Protect your property with comprehensive fire cover.',
      'Fast response for loss assessment and claims.',
      'Experienced advisors for commercial risks.',
    ],
    related: [
      { slug: 'home-insurance', label: 'Home Insurance' },
      { slug: 'engineering-insurance', label: 'Engineering Insurance' },
      { slug: 'liability-insurance', label: 'Liability Insurance' },
    ],
  },
  'marine-insurance': {
    slug: 'marine-insurance',
    title: 'Marine Insurance',
    desc: 'Protect your cargo and shipping operations with transit and marine liability coverage.',
    hero: 'Keep goods in transit, shipping vessels, and freight protected from loss and damage.',
    overview: [
      'Marine insurance covers goods, hulls, and freight during transit.',
      'Ideal for exporters, importers, and logistics businesses.',
      'Includes protection for sea, air and land transit risks.',
    ],
    benefits: [
      { title: 'Cargo Security', description: 'Cover shipments from loss, delay, and damage.' },
      { title: 'Vessel Protection', description: 'Insure hulls and equipment against marine risks.' },
      { title: 'Global Coverage', description: 'Support for domestic and international transport.' },
    ],
    features: [
      { title: 'Cargo Insurance', description: 'Protect goods against theft, damage and transit loss.' },
      { title: 'Hull Insurance', description: 'Cover vessel structure and machinery damage.' },
      { title: 'Freight Insurance', description: 'Protect freight costs during transport disruption.' },
      { title: 'Liability Support', description: 'Marine liability protection for accidents and losses.' },
    ],
    eligibility: [
      'Details of cargo, vessel, or air shipment',
      'Transport itinerary and carrier information',
      'Commercial trading documentation',
    ],
    documents: [
      'Bill of lading or airway bill',
      'Cargo invoice and packing list',
      'Shipping contract or charter party',
      'Insurance proposal form and risk details',
    ],
    process: [
      { title: 'Risk Evaluation', description: 'Assess cargo, route, and transport mode risks.' },
      { title: 'Policy Recommendation', description: 'Choose protection aligned to your logistics needs.' },
      { title: 'Documentation', description: 'Prepare shipping and cargo records for underwriting.' },
      { title: 'Claims Handling', description: 'Get support for transit loss and damage claims.' },
    ],
    faqs: [
      { question: 'Does marine insurance cover sea storms?', answer: 'Yes, most policies cover storm-related cargo and hull damage.' },
      { question: 'Is air freight covered?', answer: 'Yes, marine insurance terminology often includes air transit as cargo insurance.' },
      { question: 'Do I need customs documents?', answer: 'Customs and shipping documents help with claims and underwriting.' },
    ],
    coverage: [
      'Cargo damage and theft',
      'Hull and machinery loss',
      'Freight costs',
      'Marine liability',
    ],
    exclusions: [
      'War and strike risks unless specifically covered',
      'Delay and market value changes',
      'Improper cargo packaging',
    ],
    addOns: [
      'War risks cover',
      'Strikes and civil commotion cover',
      'Theft and pilferage protection',
      'Extended transit cover',
    ],
    premiumFactors: [
      'Cargo type and value',
      'Transit route and mode',
      'Carrier history and packaging quality',
      'Coverage terms and deductibles',
    ],
    tips: [
      'Document cargo value accurately for strong claims support.',
      'Choose coverage for the entire transit route.',
      'Use trusted carriers and packaging standards.',
    ],
    whyChoose: [
      'Marine insurance expertise for complex logistics.',
      'End-to-end support for transit risk mitigation.',
      'Fast claim assistance for cargo and vessel losses.',
    ],
    related: [
      { slug: 'fire-insurance', label: 'Fire Insurance' },
      { slug: 'engineering-insurance', label: 'Engineering Insurance' },
      { slug: 'liability-insurance', label: 'Liability Insurance' },
    ],
  },
  'engineering-insurance': {
    slug: 'engineering-insurance',
    title: 'Engineering Insurance',
    desc: 'Insurance for contractors, construction projects and plant machinery during installation and erection.',
    hero: 'Protect engineering projects with cover for machinery, erection risks, and construction liabilities.',
    overview: [
      'Engineering insurance protects assets and projects during construction and installation.',
      'Includes contractors plant and machinery, erection all risks, and third-party liability.',
      'Designed for project continuity and risk management.',
    ],
    benefits: [
      { title: 'Project Protection', description: 'Secure construction equipment and installation works.' },
      { title: 'Liability Coverage', description: 'Protect against third-party injury and property damage.' },
      { title: 'Operational Continuity', description: 'Limit financial impact from delays and equipment breakdown.' },
    ],
    features: [
      { title: 'Contractors Plant & Machinery', description: 'Cover equipment on site and in transit.' },
      { title: 'Erection All Risks', description: 'Protect installation and construction works.' },
      { title: 'Third-Party Liability', description: 'Cover liability during engineering operations.' },
      { title: 'Advance Loss of Profits', description: 'Optional cover for delay-related losses.' },
    ],
    eligibility: [
      'Project and contractor details',
      'Plant and equipment specifications',
      'Construction schedule and risk profile',
    ],
    documents: [
      'Project contract and tender documents',
      'Equipment inventory and value list',
      'Work schedule and risk assessment',
      'Contractor licence and business proof',
    ],
    process: [
      { title: 'Project Review', description: 'Analyze project scope and risk exposures.' },
      { title: 'Cover Recommendation', description: 'Select policies matching engineering needs.' },
      { title: 'Documentation', description: 'Submit project and equipment details for underwriting.' },
      { title: 'Claims Support', description: 'Handle equipment loss and delay claims effectively.' },
    ],
    faqs: [
      { question: 'What is erection all risks insurance?', answer: 'It covers construction and installation projects against material damage and loss.' },
      { question: 'Does it cover plant machinery?', answer: 'Yes, plant and machinery cover protects equipment on site and during transit.' },
      { question: 'Is third-party liability included?', answer: 'Yes, liability cover is available for project-related accidents.' },
    ],
    coverage: [
      'Erection and construction risk',
      'Plant and machinery damage',
      'Third-party liability',
      'Advance loss of profits',
    ],
    exclusions: [
      'Poor workmanship and design flaws',
      'Wear and tear',
      'Intentionally caused damage',
    ],
    addOns: [
      'Standby charges protection',
      'Testing and commissioning cover',
      'Delay in start-up cover',
      'Third-party liability extension',
    ],
    premiumFactors: [
      'Project value and duration',
      'Type of equipment and materials',
      'Site risk and safety measures',
      'Coverage options and deductibles',
    ],
    tips: [
      'Provide accurate project details for pricing.',
      'Review exclusions before buying cover.',
      'Use experienced advisors for engineering risks.',
    ],
    whyChoose: [
      'Project-specific engineering insurance solutions.',
      'Expert support for contractor risks and claims.',
      'Transparent underwriting and policy guidance.',
    ],
    related: [
      { slug: 'fire-insurance', label: 'Fire Insurance' },
      { slug: 'liability-insurance', label: 'Liability Insurance' },
      { slug: 'corporate-insurance', label: 'Corporate Insurance' },
    ],
  },
  'liability-insurance': {
    slug: 'liability-insurance',
    title: 'Liability Insurance',
    desc: 'Protect your business from third-party claims, legal expenses, and liability losses.',
    hero: 'Safeguard your business with liability insurance tailored for professional and general exposures.',
    overview: [
      'Liability insurance covers third-party injury, property damage, and legal costs.',
      'Suitable for businesses, professionals, and contractors.',
      'Provides financial protection against unforeseen claims.',
    ],
    benefits: [
      { title: 'Legal Protection', description: 'Cover legal defense costs for covered claims.' },
      { title: 'Claim Support', description: 'Get fast assistance for liability incidents.' },
      { title: 'Business Confidence', description: 'Protect your reputation and finances from claims.' },
    ],
    features: [
      { title: 'Public Liability', description: 'Cover injury or property damage to third parties.' },
      { title: 'Product Liability', description: 'Protect claims arising from product use.' },
      { title: 'Professional Indemnity', description: 'Cover professionals for service-related claims.' },
      { title: 'Employer Liability', description: 'Protect employees and workplace-related claims.' },
    ],
    eligibility: [
      'Business or professional registration details',
      'Risk profile and operations information',
      'Previous claims history',
    ],
    documents: [
      'Business registration or professional licence',
      'Policy application details',
      'Financial statements if required',
      'Previous insurance or claims records',
    ],
    process: [
      { title: 'Risk Assessment', description: 'Analyze your business exposures and coverage gaps.' },
      { title: 'Policy Recommendation', description: 'Choose liability products suited to your operations.' },
      { title: 'Application Submission', description: 'Provide business details and documentation.' },
      { title: 'Claims Assistance', description: 'Access help for legal defense and claim settlement.' },
    ],
    faqs: [
      { question: 'What is public liability insurance?', answer: 'It covers your legal liability to third parties for injury or property damage.' },
      { question: 'Do professionals need liability cover?', answer: 'Yes, professional indemnity protects against claims from advice or services provided.' },
      { question: 'Is product liability included?', answer: 'Product liability can be included to protect against consumer claims.' },
    ],
    coverage: [
      'Third-party injury and property damage',
      'Professional negligence',
      'Employer liability',
      'Product liability',
    ],
    exclusions: [
      'Intentional acts and criminal behavior',
      'Contractual liability outside policy terms',
      'Known claims not disclosed',
    ],
    addOns: [
      'Legal expenses cover',
      'Product recall protection',
      'Cyber liability extension',
      'Directors and officers liability',
    ],
    premiumFactors: [
      'Business size and industry',
      'Claims history',
      'Policy limits and deductibles',
      'Coverage scope and add-ons',
    ],
    tips: [
      'Disclose your risk exposures accurately.',
      'Choose limits that match contract requirements.',
      'Maintain claims records for renewal.',
    ],
    whyChoose: [
      'Liability solutions tailored for businesses.',
      'Expert support for claims and legal costs.',
      'Comprehensive protection for multiple exposures.',
    ],
    related: [
      { slug: 'corporate-insurance', label: 'Corporate Insurance' },
      { slug: 'engineering-insurance', label: 'Engineering Insurance' },
      { slug: 'business-loan', label: 'Business Loan' },
    ],
  },
  'group-health-insurance': {
    slug: 'group-health-insurance',
    title: 'Group Health Insurance',
    desc: 'Employee health coverage with cashless benefits, wellness support, and easy policy administration.',
    hero: 'Offer your team medical protection through a single group policy with streamlined service.',
    overview: [
      'Group health insurance covers employees and dependents under one plan.',
      'It simplifies policy administration and claim support for businesses.',
      'Perfect for companies that want strong employee benefits.',
    ],
    benefits: [
      { title: 'Employee Wellbeing', description: 'Attract and retain talent with quality health coverage.' },
      { title: 'Cashless Hospitalization', description: 'Enable employees to use network hospitals without upfront payment.' },
      { title: 'Flexible Benefits', description: 'Tailor cover to your workforce and budget.' },
    ],
    features: [
      { title: 'Group Cover', description: 'Policy for employees and eligible dependents.' },
      { title: 'Wellness Programs', description: 'Preventive health checks and support services.' },
      { title: 'Claim Assistance', description: 'Dedicated support for employee claims.' },
      { title: 'Renewal Simplicity', description: 'Policy renewal managed with minimal disruption.' },
    ],
    eligibility: [
      'Employers with a minimum number of employees as required by insurers',
      'Employee details and dependent information',
      'Business registration documents',
    ],
    documents: [
      'Company registration proof',
      'Employee list and declarations',
      'Previous group insurance details if any',
      'Health declarations for dependents if required',
    ],
    process: [
      { title: 'Plan Design', description: 'Create a group policy suited to your workforce.' },
      { title: 'Employee Enrollment', description: 'Collect details and submit enrollment forms.' },
      { title: 'Policy Issuance', description: 'Receive group insurance documents and employee cards.' },
      { title: 'Claim Support', description: 'Assist employees with cashless claims and approvals.' },
    ],
    faqs: [
      { question: 'Can family members be included?', answer: 'Yes, dependents may be included as per policy terms.' },
      { question: 'How are premiums calculated?', answer: 'Based on employee count, age profile, and chosen benefits.' },
      { question: 'Does it cover pre-existing conditions?', answer: 'Coverage depends on insurer terms and waiting periods.' },
    ],
    coverage: [
      'Hospitalization for employees and dependents',
      'Cashless treatment',
      'Wellness check-ups',
      'Maternity and daycare treatment options',
    ],
    exclusions: [
      'Unspecified non-medical expenses',
      'Treatments not covered by network',
      'Self-inflicted injuries',
    ],
    addOns: [
      'Employee wellness programs',
      'Maternity benefits for dependents',
      'Hospital cash',
      'Mental health support',
    ],
    premiumFactors: [
      'Employee count and age distribution',
      'Coverage limits and benefits selected',
      'Claims history and health profile',
      'Industry risk and location factors',
    ],
    tips: [
      'Review employee needs before selecting benefits.',
      'Use wellness incentives to reduce claims.',
      'Maintain accurate employee records for renewals.',
    ],
    whyChoose: [
      'Streamlined group health planning and claims support.',
      'Employee-friendly administration and network access.',
      'Custom solutions for corporate wellbeing.',
    ],
    related: [
      { slug: 'health-insurance', label: 'Health Insurance' },
      { slug: 'corporate-insurance', label: 'Corporate Insurance' },
      { slug: 'term-life-insurance', label: 'Term Life Insurance' },
    ],
  },
  'corporate-insurance': {
    slug: 'corporate-insurance',
    title: 'Corporate Insurance',
    desc: 'Comprehensive business insurance for property, liability, employee benefits and executive protection.',
    hero: 'Protect your business with tailored corporate coverage for every operational risk.',
    overview: [
      'Corporate insurance covers business assets, liabilities and employee welfare.',
      'Designed for companies seeking integrated protection and risk management.',
      'Includes property, liability, health, and financial risk solutions.',
    ],
    benefits: [
      { title: 'Business Continuity', description: 'Minimize financial loss from unexpected business interruptions.' },
      { title: 'Liability Protection', description: 'Insulate the company from third-party claims.' },
      { title: 'Employee Benefits', description: 'Offer health coverage and risk protection to staff.' },
    ],
    features: [
      { title: 'Property and Fire Cover', description: 'Protect office, factory and assets from damage.' },
      { title: 'Liability Insurance', description: 'Cover third-party and professional risks.' },
      { title: 'Employee Benefits', description: 'Offer group health and personal accident cover.' },
      { title: 'D&O Protection', description: 'Protect directors and officers against management liability.' },
    ],
    eligibility: [
      'Company registration and incorporation details',
      'Asset and employee information',
      'Risk profile and business segment details',
    ],
    documents: [
      'Business registration proof',
      'Financial and asset statements',
      'Employee benefit details',
      'Risk assessment documentation',
    ],
    process: [
      { title: 'Risk Assessment', description: 'Evaluate business exposures and insurance needs.' },
      { title: 'Policy Design', description: 'Assemble a corporate insurance program.' },
      { title: 'Documentation', description: 'Submit company and asset records for underwriting.' },
      { title: 'Renewals & Claims', description: 'Manage corporate cover renewals and claim support.' },
    ],
    faqs: [
      { question: 'What is corporate insurance?', answer: 'A customized insurance package for business risks and assets.' },
      { question: 'Can I add executive protection?', answer: 'Yes, D&O and key-man insurance are available as add-ons.' },
      { question: 'Is employee health included?', answer: 'Group health and employee benefits can be bundled into corporate cover.' },
    ],
    coverage: [
      'Business property',
      'Liability claims',
      'Employee benefits',
      'Management protection',
    ],
    exclusions: [
      'Fraud and criminal acts',
      'Unreported risks',
      'Deliberate damage',
    ],
    addOns: [
      'Directors & officers cover',
      'Key man insurance',
      'Group health benefits',
      'Cyber liability extensions',
    ],
    premiumFactors: [
      'Company size and revenue',
      'Industry risk and location',
      'Coverage selections and limits',
      'Claims experience',
    ],
    tips: [
      'Bundle related covers for efficient protection.',
      'Update asset values regularly for accurate coverage.',
      'Train teams on risk management to reduce premiums.',
    ],
    whyChoose: [
      'Corporate risk solutions built for modern businesses.',
      'Advisory support across insurance and claims.',
      'Trusted by business owners for smart protection.',
    ],
    related: [
      { slug: 'group-health-insurance', label: 'Group Health Insurance' },
      { slug: 'liability-insurance', label: 'Liability Insurance' },
      { slug: 'business-loan', label: 'Business Loan' },
    ],
  },
  'mutual-funds': {
    slug: 'mutual-funds',
    title: 'Mutual Funds',
    desc: 'Invest across equity, debt, and hybrid funds to build wealth with professional guidance.',
    hero: 'Grow your portfolio with mutual funds designed for long-term financial goals.',
    overview: [
      'Mutual funds pool investor capital to invest in diversified assets.',
      'Choose equity, debt or hybrid funds based on risk appetite.',
      'Ideal for long-term goals such as wealth creation and retirement.',
    ],
    benefits: [
      { title: 'Diversified Investing', description: 'Spread risk across stocks, bonds and multiple sectors.' },
      { title: 'Professional Management', description: 'Fund managers manage investments on your behalf.' },
      { title: 'Liquidity', description: 'Buy and redeem units as needed with transparent pricing.' },
    ],
    features: [
      { title: 'Equity Funds', description: 'Growth-focused investments in stocks.' },
      { title: 'Debt Funds', description: 'Income-oriented investments in bonds and securities.' },
      { title: 'Hybrid Funds', description: 'Blend equity and debt for balanced returns.' },
      { title: 'SIP Option', description: 'Systematic investment plan to build wealth over time.' },
    ],
    eligibility: [
      'Resident individuals and HUFs',
      'PAN card and KYC compliance',
      'Bank account details for transactions',
    ],
    documents: [
      'PAN card',
      'Aadhaar or address proof',
      'Cancelled cheque or bank proof',
      'KYC documents',
    ],
    process: [
      { title: 'Goal Planning', description: 'Define your investment objectives and horizon.' },
      { title: 'Fund Selection', description: 'Choose mutual funds aligned to your goals.' },
      { title: 'Investment', description: 'Start with lump sum or SIP contributions.' },
      { title: 'Monitoring', description: 'Track performance and review portfolio regularly.' },
    ],
    faqs: [
      { question: 'What is a mutual fund?', answer: 'A pooled investment vehicle managed by professional fund managers.' },
      { question: 'Can I invest with small amounts?', answer: 'Yes, SIPs allow small monthly investments.' },
      { question: 'Is it safe to invest in mutual funds?', answer: 'Risk depends on fund type; equity funds are higher risk than debt funds.' },
    ],
    coverage: [
      'Equity market exposure',
      'Debt instruments',
      'Hybrid asset allocation',
      'Fund manager diversification',
    ],
    exclusions: [
      'Guarantee of returns',
      'Protection against market volatility',
      'Coverage for non-financial needs',
    ],
    addOns: [
      'SIP plan setup',
      'Systematic withdrawal plan',
      'Top-up investments',
      'Goal-based portfolio planning',
    ],
    premiumFactors: [
      'Fund category and risk profile',
      'Market conditions',
      'Fund expense ratio',
      'Investment horizon',
    ],
    tips: [
      'Invest consistently through SIPs.',
      'Diversify across fund categories.',
      'Review performance against benchmarks.',
    ],
    whyChoose: [
      'Long-term investing advice with clarity.',
      'Goal-based fund selection and monitoring.',
      'Support for SIP and financial planning.',
    ],
    related: [
      { slug: 'sip-investment', label: 'SIP Investment' },
      { slug: 'term-life-insurance', label: 'Term Life Insurance' },
      { slug: 'home-loan', label: 'Home Loan' },
    ],
  },
  'sip-investment': {
    slug: 'sip-investment',
    title: 'SIP Investment',
    desc: 'Systematic investment plans for disciplined wealth creation through regular contributions.',
    hero: 'Build wealth steadily with SIPs that fit your budget and long-term goals.',
    overview: [
      'SIPs invest fixed amounts regularly into mutual funds.',
      'It helps average cost and encourages disciplined investing.',
      'Ideal for long-term goals like retirement, education, and wealth growth.',
    ],
    benefits: [
      { title: 'Rupee Cost Averaging', description: 'Mitigate volatility by investing regularly over time.' },
      { title: 'Low Initial Investment', description: 'Start SIPs with small monthly amounts.' },
      { title: 'Goal Planning', description: 'Align SIPs with financial objectives and timelines.' },
    ],
    features: [
      { title: 'Regular Investing', description: 'Invest monthly or quarterly in mutual funds.' },
      { title: 'Auto Debit Facility', description: 'Set up automatic payments from your bank account.' },
      { title: 'Flexible Top-Ups', description: 'Increase your SIP amount as goals evolve.' },
      { title: 'Redemption Options', description: 'Withdraw funds when you need them.' },
    ],
    eligibility: [
      'PAN card and KYC registration',
      'Active bank account for auto debit',
      'Resident investor status',
    ],
    documents: [
      'PAN card',
      'Aadhaar or address proof',
      'Cancelled cheque or bank statement',
      'KYC documents',
    ],
    process: [
      { title: 'Plan Selection', description: 'Choose fund and SIP frequency.' },
      { title: 'KYC Completion', description: 'Complete KYC to unlock SIP investments.' },
      { title: 'SIP Setup', description: 'Authorize auto debit and begin investments.' },
      { title: 'Review Portfolio', description: 'Track returns and rebalance as necessary.' },
    ],
    faqs: [
      { question: 'How much should I invest in a SIP?', answer: 'Choose an amount that fits your budget and goals.' },
      { question: 'Can I stop SIP anytime?', answer: 'Yes, SIPs can be paused or stopped as needed.' },
      { question: 'Do SIPs guarantee returns?', answer: 'No, returns depend on market performance.' },
    ],
    coverage: [
      'Monthly mutual fund investments',
      'Equity, debt, and hybrid exposure',
      'Discipline in investing',
      'Long-term wealth building',
    ],
    exclusions: [
      'Guaranteed returns',
      'Protection from market losses',
      'Short-term market timing benefits',
    ],
    addOns: [
      'Top-up SIPs',
      'SIP pause/resume options',
      'Goal-based planning',
      'Systematic withdrawal plans',
    ],
    premiumFactors: [
      'Fund performance and expense ratio',
      'Investment duration',
      'SIP amount and frequency',
      'Market volatility',
    ],
    tips: [
      'Start SIPs with a long-term horizon.',
      'Review fund performance periodically.',
      'Increase your SIP amount over time.',
    ],
    whyChoose: [
      'Goal-driven SIP investment advice.',
      'Support for selecting the right funds.',
      'Discipline and performance tracking for long-term growth.',
    ],
    related: [
      { slug: 'mutual-funds', label: 'Mutual Funds' },
      { slug: 'home-loan', label: 'Home Loan' },
      { slug: 'term-life-insurance', label: 'Term Life Insurance' },
    ],
  },
  'car-loan': {
    slug: 'car-loan',
    title: 'Car Loan',
    desc: 'Flexible car loan options for new and used vehicles with easy approvals and competitive EMI plans.',
    hero: 'Drive your dream car with finance solutions that match your budget and repayment goals.',
    overview: [
      'Car loans help you purchase a vehicle with structured EMI payments.',
      'Suitable for new and pre-owned cars with transparent interest rates.',
      'Includes support for approval, documentation, and disbursement.',
    ],
    benefits: [
      { title: 'Fast Approval', description: 'Quick loan decisions with minimal paperwork.' },
      { title: 'Flexible Tenure', description: 'Choose EMIs that fit your monthly budget.' },
      { title: 'Competitive Rates', description: 'Access lenders with attractive interest terms.' },
    ],
    features: [
      { title: 'New Car Loans', description: 'Finance new car purchases with easy terms.' },
      { title: 'Used Car Loans', description: 'Support for pre-owned vehicle financing.' },
      { title: 'Top-up Loans', description: 'Add additional funding if needed later.' },
      { title: 'Loan Restructuring', description: 'Manage EMIs through resettlement and balance transfer.' },
    ],
    eligibility: [
      'Salaried or self-employed applicants with stable income',
      'Minimum age and employment criteria',
      'Good credit and identity documents',
    ],
    documents: [
      'Income proof and salary slips',
      'Identity and address proof',
      'Vehicle quotation and RC book for used cars',
      'Bank statements and KYC documents',
    ],
    process: [
      { title: 'Loan Assessment', description: 'Review your income, credit and repayment capacity.' },
      { title: 'Lender Selection', description: 'Match with lenders offering the best terms.' },
      { title: 'Application Submission', description: 'Submit documents and complete verification.' },
      { title: 'Disbursal', description: 'Receive funds and complete car purchase.' },
    ],
    faqs: [
      { question: 'Can I get a loan for a used car?', answer: 'Yes, used car loans are available with competitive rates.' },
      { question: 'What is the minimum down payment?', answer: 'Down payment depends on lender policies and loan-to-value ratio.' },
      { question: 'Can I prepay my car loan?', answer: 'Yes, many lenders allow prepayment with minimal charges.' },
    ],
    coverage: [
      'New and used car purchase financing',
      'EMI and tenure flexibility',
      'Loan top-ups and restructuring',
      'Balance transfer options',
    ],
    exclusions: [
      'Unverifiable income sources',
      'Poor credit history without suitable security',
      'Loans for non-vehicle purposes',
    ],
    addOns: [
      'EMI protection cover',
      'Loan top-up',
      'Balance transfer',
      'Insurance bundle options',
    ],
    premiumFactors: [
      'Loan amount and tenor',
      'Credit score',
      'Income stability',
      'Vehicle age and value',
    ],
    tips: [
      'Compare lenders for the best rate.',
      'Keep your credit score healthy.',
      'Choose tenure that matches your cash flow.',
    ],
    whyChoose: [
      'Fast car loan approvals.',
      'Flexible EMI structures.',
      'Personalised finance guidance.',
    ],
    related: [
      { slug: 'vehicle-finance', label: 'Vehicle Finance' },
      { slug: 'car-insurance', label: 'Car Insurance' },
      { slug: 'home-loan', label: 'Home Loan' },
    ],
  },
  'bike-loan': {
    slug: 'bike-loan',
    title: 'Bike Loan',
    desc: 'Affordable financing for two-wheelers with easy documentation and fast disbursal.',
    hero: 'Own your bike sooner with bike loans tailored for commuters and riders.',
    overview: [
      'Bike loans support purchase of scooters and motorcycles.',
      'Offers flexible EMIs and quick processing.',
      'Ideal for first-time buyers and repeat customers.',
    ],
    benefits: [
      { title: 'Quick Approval', description: 'Get finance with minimal paperwork.' },
      { title: 'Flexible Repayments', description: 'Choose a tenure that fits your budget.' },
      { title: 'Low Down Payment', description: 'Start with affordable down payment options.' },
    ],
    features: [
      { title: 'New Bike Loans', description: 'Financing for brand-new two-wheelers.' },
      { title: 'Used Bike Loans', description: 'Loans for pre-owned bikes with flexible terms.' },
      { title: 'EMI Planning', description: 'Structure payments to avoid cash flow pressure.' },
      { title: 'Easy Documentation', description: 'Submit identity, income and bike details.' },
    ],
    eligibility: [
      'Salaried or self-employed applicants',
      'Valid driver’s licence',
      'Stable monthly income',
    ],
    documents: [
      'Salary slips or income proof',
      'Identity and address proof',
      'Driver’s licence',
      'Bank statements and KYC documents',
    ],
    process: [
      { title: 'Pre-qualification', description: 'Check your loan eligibility and terms.' },
      { title: 'Application', description: 'Submit documents and bike quotation.' },
      { title: 'Verification', description: 'Complete lender verification and approval.' },
      { title: 'Disbursal', description: 'Receive funds and finalize the bike purchase.' },
    ],
    faqs: [
      { question: 'Can I finance a used bike?', answer: 'Yes, used bike loans are available with competitive rates.' },
      { question: 'Is a driving licence required?', answer: 'Yes, a valid licence is generally required for bike loan approval.' },
      { question: 'How much can I borrow?', answer: 'Loan amount depends on bike value and your repayment capacity.' },
    ],
    coverage: [
      'Two-wheeler purchase financing',
      'Flexible EMI options',
      'Loan top-ups',
      'Quick disbursal',
    ],
    exclusions: [
      'Non-compliant documentation',
      'Low income or poor credit',
      'Financing for unregistered bikes',
    ],
    addOns: [
      'EMI protection plan',
      'Top-up loan',
      'Balance transfer',
      'Insurance-bundled loan',
    ],
    premiumFactors: [
      'Bike value and age',
      'Credit score',
      'Tenure and down payment',
      'Income and stability',
    ],
    tips: [
      'Choose a comfortable EMI term.',
      'Maintain a good credit score.',
      'Keep all documents current and accurate.',
    ],
    whyChoose: [
      'Two-wheeler finance with fast approval.',
      'Simple documentation and customer support.',
      'Affordable EMIs for every rider.',
    ],
    related: [
      { slug: 'bike-insurance', label: 'Bike Insurance' },
      { slug: 'car-loan', label: 'Car Loan' },
      { slug: 'personal-accident-insurance', label: 'Personal Accident Insurance' },
    ],
  },
  'commercial-vehicle-loan': {
    slug: 'commercial-vehicle-loan',
    title: 'Commercial Vehicle Loan',
    desc: 'Finance solutions for trucks, tempos, and commercial fleets with flexible terms and tailored support.',
    hero: 'Fuel your business growth with commercial vehicle loans designed for fleet owners.',
    overview: [
      'Commercial vehicle loans support purchases of trucks, buses and cargo vehicles.',
      'Designed for business use with tailored repayment plans.',
      'Includes assistance for documentation and approvals.',
    ],
    benefits: [
      { title: 'Business-Friendly Terms', description: 'Loan structures made for commercial cash flows.' },
      { title: 'Fast Processing', description: 'Quick verification and fund disbursal.' },
      { title: 'Fleet Expansion', description: 'Support scaling your commercial vehicle operations.' },
    ],
    features: [
      { title: 'Truck and Bus Loans', description: 'Finance for heavy vehicles and passenger transport.' },
      { title: 'Tempo and Goods Carrier Loans', description: 'Specialized loans for delivery and cargo vehicles.' },
      { title: 'Flexible Tenures', description: 'Choose repayment terms aligned to business revenue.' },
      { title: 'Documentation Support', description: 'Assistance with vehicle and business paperwork.' },
    ],
    eligibility: [
      'Business registration or fleet ownership proof',
      'Commercial RC and vehicle details',
      'Business financial statements and bank records',
    ],
    documents: [
      'Business registration and GST details',
      'Vehicle quotations and RC documentation',
      'Income proof and bank statements',
      'Identity and address proof',
    ],
    process: [
      { title: 'Business Evaluation', description: 'Review your commercial vehicle needs and repayment ability.' },
      { title: 'Lender Match', description: 'Find lenders that specialize in commercial vehicle finance.' },
      { title: 'Application', description: 'Submit documents and complete business verification.' },
      { title: 'Disbursal', description: 'Receive funds to purchase commercial vehicles.' },
    ],
    faqs: [
      { question: 'Can I finance a fleet of commercial vehicles?', answer: 'Yes, fleet financing is available for multiple vehicles.' },
      { question: 'What documents are required?', answer: 'Business proof, RC details, income statements, and KYC documents are required.' },
      { question: 'Is down payment necessary?', answer: 'Most lenders require a down payment based on vehicle value.' },
    ],
    coverage: [
      'Heavy vehicle financing',
      'Tempo and goods carrier loans',
      'Flexible tenure options',
      'Business-oriented repayment plans',
    ],
    exclusions: [
      'Non-commercial usage',
      'Poorly documented businesses',
      'Unregistered vehicles',
    ],
    addOns: [
      'Fleet financing options',
      'Loan top-up',
      'EMI protection cover',
      'Insurance bundling',
    ],
    premiumFactors: [
      'Vehicle type and capacity',
      'Business turnover',
      'Loan amount and tenor',
      'Credit rating and repayment history',
    ],
    tips: [
      'Choose a loan term that aligns with revenue cycles.',
      'Keep business financials organized for approval.',
      'Consider insurance bundling for asset protection.',
    ],
    whyChoose: [
      'Commercial vehicle finance expertise.',
      'Support for fleet and business requirements.',
      'Fast approvals and transparent terms.',
    ],
    related: [
      { slug: 'commercial-vehicle-insurance', label: 'Commercial Vehicle Insurance' },
      { slug: 'rto-services', label: 'RTO Services' },
      { slug: 'business-loan', label: 'Business Loan' },
    ],
  },
  'rto-services': {
    slug: 'rto-services',
    title: 'RTO Services',
    desc: 'Complete RTO services including fitness renewal, permits, tax, transfers, and smart card issuance.',
    hero: 'Manage your vehicle compliance and documentation through expert RTO service support.',
    overview: [
      'RTO services help maintain vehicle legality and compliance.',
      'Includes permits, registration changes, renewals, NOC, and more.',
      'Ideal for private owners, commercial fleets, and businesses.',
    ],
    benefits: [
      { title: 'Comprehensive Support', description: 'Handle all RTO needs from fitness to registration with one partner.' },
      { title: 'Regulatory Compliance', description: 'Stay compliant with current transport authority rules.' },
      { title: 'Fast Documentation', description: 'Streamline permit and transfer paperwork with expert help.' },
    ],
    features: [
      { title: 'Fitness Renewal', description: 'Keep commercial vehicles roadworthy and certified.' },
      { title: 'Permit Renewal', description: 'Renew national and state permits on time.' },
      { title: 'Road Tax', description: 'Manage tax payments and receipts accurately.' },
      { title: 'Ownership Transfer', description: 'Support sales and ownership change paperwork.' },
    ],
    eligibility: [
      'Vehicle registration and owner details',
      'Permit or transport licence documentation',
      'RTO-specific compliance certificates',
    ],
    documents: [
      'RC book and permit documents',
      'Owner identity and address proof',
      'NOC or loan closure papers if applicable',
      'PUC certificate and fitness reports',
    ],
    process: [
      { title: 'Document Collection', description: 'Gather all required RTO documents and permits.' },
      { title: 'Application Filing', description: 'Submit requests for renewals, transfers, and NOCs.' },
      { title: 'RTO Coordination', description: 'Follow up with transport authorities for approvals.' },
      { title: 'Delivery', description: 'Receive updated RC, permits, and documents promptly.' },
    ],
    faqs: [
      { question: 'What is fitness renewal?', answer: 'A certification process to ensure commercial vehicles meet road safety standards.' },
      { question: 'Do I need a NOC for ownership transfer?', answer: 'Yes, NOC is usually required when transferring vehicles with loans or different states.' },
      { question: 'Can RTO services be handled online?', answer: 'Many services can be initiated online, but some may require physical verification.' },
    ],
    coverage: [
      'Fitness renewal',
      'Permit renewal and issuance',
      'Road tax payment',
      'RC transfer and registration changes',
    ],
    exclusions: [
      'Illegal vehicle modifications',
      'Expired documents beyond grace period',
      'Non-compliant vehicles',
    ],
    addOns: [
      'PUC reminders',
      'Smart card issuance',
      'Fancy number allocation',
      'National/state permit support',
    ],
    premiumFactors: [
      'Vehicle class and usage',
      'State transport regulations',
      'Permit type required',
      'Documentation completeness',
    ],
    tips: [
      'Keep RTO documents updated before expiry.',
      'Use expert help for interstate transfers.',
      'Track tax and permit renewals proactively.',
    ],
    whyChoose: [
      'Full-service RTO support for every vehicle need.',
      'Quick permit and documentation processing.',
      'Expert handling of compliances and approvals.',
    ],
    related: [
      { slug: 'rc-transfer', label: 'RC Transfer' },
      { slug: 'hypothecation', label: 'Hypothecation' },
      { slug: 'permit', label: 'Permit' },
    ],
  },
}
